//! TCP/IP network stack — smoltcp adapter + DHCP + DNS + TCP connections.
//!
//! This module bridges any NIC driver to smoltcp's TCP/IP implementation.
//! It provides:
//!   - SmoltcpAdapter: wraps Box<dyn NicDriver> to implement smoltcp's Device trait
//!   - NetworkStack: manages the IP interface, socket set, DHCP, DNS, TCP
//!
//! The stack uses a polling model: call poll() frequently to process
//! incoming/outgoing packets. The NetworkAgent (in agent.rs) does this
//! every SART tick.

use smoltcp::iface::{Config, Interface, SocketHandle, SocketSet};
use smoltcp::phy::{Device, DeviceCapabilities, Medium, RxToken, TxToken};
use smoltcp::socket::{dhcpv4, dns, tcp};
use smoltcp::time::Instant;
use smoltcp::wire::{EthernetAddress, HardwareAddress, IpCidr, Ipv4Address, Ipv4Cidr};

use alloc::{boxed::Box, vec, vec::Vec};

use crate::nic::NicDriver;

// ---------------------------------------------------------------------------
// smoltcp Device adapter — wraps any NicDriver
// ---------------------------------------------------------------------------

/// Wraps a NIC driver to implement smoltcp's `Device` trait.
///
/// smoltcp doesn't talk to hardware directly. Instead, it calls
/// receive() and transmit() on a Device to get/put Ethernet frames.
/// This adapter bridges that interface to any NIC driver via the NicDriver trait.
pub struct SmoltcpAdapter {
    inner: Box<dyn NicDriver>,
    /// Frames received from hardware, waiting for smoltcp to process
    rx_queue: Vec<Vec<u8>>,
    /// Frames generated by smoltcp, waiting to be sent to hardware
    tx_queue: Vec<Vec<u8>>,
}

impl SmoltcpAdapter {
    pub fn new(dev: Box<dyn NicDriver>) -> Self {
        Self {
            inner: dev,
            rx_queue: Vec::new(),
            tx_queue: Vec::new(),
        }
    }

    pub fn mac(&self) -> EthernetAddress {
        EthernetAddress(self.inner.mac_address())
    }

    /// Move packets between the hardware and our queues.
    ///
    /// Called before every smoltcp poll to:
    /// 1. Pull received frames from the NIC into rx_queue
    /// 2. Push queued TX frames from tx_queue to the NIC
    pub fn poll_hardware(&mut self) {
        // Pull all available RX frames
        loop {
            let mut buf = vec![0u8; 1514];
            match self.inner.recv_frame(&mut buf) {
                Some(len) => {
                    buf.truncate(len);
                    self.rx_queue.push(buf);
                }
                None => break,
            }
        }
        // Flush all queued TX frames
        for frame in self.tx_queue.drain(..) {
            self.inner.send_frame(&frame);
        }
    }
}

/// Token that smoltcp uses to consume one received Ethernet frame.
pub struct SmoltcpRxToken(Vec<u8>);

/// Token that smoltcp uses to send one Ethernet frame.
pub struct SmoltcpTxToken<'a>(&'a mut Vec<Vec<u8>>);

impl RxToken for SmoltcpRxToken {
    fn consume<R, F: FnOnce(&mut [u8]) -> R>(mut self, f: F) -> R {
        f(&mut self.0)
    }
}

impl<'a> TxToken for SmoltcpTxToken<'a> {
    fn consume<R, F: FnOnce(&mut [u8]) -> R>(self, len: usize, f: F) -> R {
        let mut buf = vec![0u8; len];
        let result = f(&mut buf);
        self.0.push(buf);
        result
    }
}

impl Device for SmoltcpAdapter {
    type RxToken<'a> = SmoltcpRxToken where Self: 'a;
    type TxToken<'a> = SmoltcpTxToken<'a> where Self: 'a;

    fn receive(&mut self, _timestamp: Instant) -> Option<(SmoltcpRxToken, SmoltcpTxToken<'_>)> {
        if self.rx_queue.is_empty() {
            return None;
        }
        let frame = self.rx_queue.remove(0);
        Some((SmoltcpRxToken(frame), SmoltcpTxToken(&mut self.tx_queue)))
    }

    fn transmit(&mut self, _timestamp: Instant) -> Option<SmoltcpTxToken<'_>> {
        Some(SmoltcpTxToken(&mut self.tx_queue))
    }

    fn capabilities(&self) -> DeviceCapabilities {
        let mut caps = DeviceCapabilities::default();
        caps.medium = Medium::Ethernet;
        caps.max_transmission_unit = 1514;
        caps
    }
}

// ---------------------------------------------------------------------------
// NetworkStack — the full TCP/IP interface
// ---------------------------------------------------------------------------

/// Get current time as a smoltcp Instant.
///
/// Uses the kernel timer (100 Hz tick → 10ms resolution). The extern
/// function is provided by the kernel crate's timer module.
fn now() -> Instant {
    extern "Rust" {
        fn kernel_milliseconds() -> u64;
    }
    Instant::from_millis(unsafe { kernel_milliseconds() } as i64)
}

/// Milliseconds since boot (for timeout calculations).
fn kernel_ms() -> u64 {
    extern "Rust" {
        fn kernel_milliseconds() -> u64;
    }
    unsafe { kernel_milliseconds() }
}

/// The complete network stack: NIC adapter + smoltcp interface + sockets.
///
/// Provides DHCP, DNS resolution, and TCP connections. The HTTP/TLS
/// layers in tls.rs and http.rs build on top of this.
pub struct NetworkStack {
    pub adapter: SmoltcpAdapter,
    pub interface: Interface,
    pub sockets: SocketSet<'static>,
    pub ip_addr: Option<Ipv4Address>,
    pub gateway: Option<Ipv4Address>,
    pub dns_server: Option<Ipv4Address>,
}

impl NetworkStack {
    /// Create a new network stack wrapping the given NIC driver.
    /// The stack starts with no IP address — call run_dhcp() to acquire one.
    pub fn new(dev: Box<dyn NicDriver>) -> Self {
        let mut adapter = SmoltcpAdapter::new(dev);
        let mac = adapter.mac();
        let config = Config::new(HardwareAddress::Ethernet(mac));
        let interface = Interface::new(config, &mut adapter, now());
        Self {
            adapter,
            interface,
            sockets: SocketSet::new(vec![]),
            ip_addr: None,
            gateway: None,
            dns_server: None,
        }
    }

    /// Process pending network I/O.
    ///
    /// Must be called frequently (every SART tick = 10ms) to:
    /// 1. Pull received frames from NIC hardware
    /// 2. Let smoltcp process all protocol state machines
    /// 3. Push outgoing frames to NIC hardware
    pub fn poll(&mut self) {
        self.adapter.poll_hardware();
        self.interface
            .poll(now(), &mut self.adapter, &mut self.sockets);
        // Flush any frames smoltcp generated during poll
        self.adapter.poll_hardware();
    }

    /// Run DHCP to acquire an IP address, gateway, and DNS server.
    ///
    /// Blocks (with HLT-based power-saving) until DHCP completes or
    /// times out after 10 seconds.
    pub fn run_dhcp(&mut self) -> Result<Ipv4Address, &'static str> {
        let dhcp_handle = self.sockets.add(dhcpv4::Socket::new());
        let deadline_ms = kernel_ms() + 10_000;

        loop {
            self.poll();

            let event = self.sockets.get_mut::<dhcpv4::Socket>(dhcp_handle).poll();
            if let Some(dhcpv4::Event::Configured(config)) = event {
                let ip = config.address.address();
                let prefix_len = config.address.prefix_len();

                self.ip_addr = Some(ip);
                self.gateway = config.router;
                self.dns_server = config.dns_servers.first().copied();

                // Apply the acquired IP address to the interface
                self.interface.update_ip_addrs(|addrs| {
                    addrs.push(IpCidr::Ipv4(Ipv4Cidr::new(ip, prefix_len))).ok();
                });
                // Set the default gateway for outbound traffic
                if let Some(gw) = config.router {
                    self.interface.routes_mut().add_default_ipv4_route(gw).ok();
                }

                return Ok(ip);
            }

            if kernel_ms() > deadline_ms {
                return Err("DHCP timeout");
            }
            x86_64::instructions::hlt();
        }
    }

    /// Resolve a hostname to an IPv4 address using the DHCP-provided DNS server.
    ///
    /// Blocks until the DNS response arrives or times out after 5 seconds.
    pub fn resolve(&mut self, hostname: &str) -> Result<Ipv4Address, &'static str> {
        let dns_server = self.dns_server.ok_or("No DNS server")?;
        let servers = [smoltcp::wire::IpAddress::Ipv4(dns_server)];
        let dns_socket = dns::Socket::new(&servers, vec![]);
        let handle = self.sockets.add(dns_socket);

        let query = self
            .sockets
            .get_mut::<dns::Socket>(handle)
            .start_query(self.interface.context(), hostname, smoltcp::wire::DnsQueryType::A)
            .map_err(|_| "DNS query failed")?;

        let deadline_ms = kernel_ms() + 5_000;

        loop {
            self.poll();

            match self
                .sockets
                .get_mut::<dns::Socket>(handle)
                .get_query_result(query)
            {
                Ok(addrs) => {
                    for addr in addrs.iter() {
                        let smoltcp::wire::IpAddress::Ipv4(ip) = addr;
                        return Ok(*ip);
                    }
                    return Err("No A record found");
                }
                Err(dns::GetQueryResultError::Pending) => {}
                Err(_) => return Err("DNS query error"),
            }

            if kernel_ms() > deadline_ms {
                return Err("DNS timeout");
            }
            x86_64::instructions::hlt();
        }
    }

    /// Open a TCP connection to a remote IPv4 address and port.
    ///
    /// Blocks until the TCP handshake completes or times out after 5 seconds.
    /// Returns a SocketHandle that can be used with tcp_send/tcp_recv or
    /// passed to the TLS layer.
    pub fn tcp_connect(
        &mut self,
        remote_ip: Ipv4Address,
        port: u16,
    ) -> Result<SocketHandle, &'static str> {
        use smoltcp::wire::{IpAddress, IpEndpoint};

        let rx_buffer = tcp::SocketBuffer::new(vec![0u8; 8192]);
        let tx_buffer = tcp::SocketBuffer::new(vec![0u8; 8192]);
        let socket = tcp::Socket::new(rx_buffer, tx_buffer);
        let handle = self.sockets.add(socket);

        // Pick an ephemeral local port based on current time
        let local_port = 49152u16.wrapping_add((kernel_ms() % 16384) as u16);
        let remote = IpEndpoint::new(IpAddress::Ipv4(remote_ip), port);

        self.sockets
            .get_mut::<tcp::Socket>(handle)
            .connect(self.interface.context(), remote, local_port)
            .map_err(|_| "TCP connect failed")?;

        let deadline_ms = kernel_ms() + 5_000;

        loop {
            self.poll();
            let state = self.sockets.get::<tcp::Socket>(handle).state();

            if state == tcp::State::Established {
                return Ok(handle);
            }
            if matches!(state, tcp::State::Closed | tcp::State::TimeWait) {
                return Err("TCP connection refused");
            }
            if kernel_ms() > deadline_ms {
                return Err("TCP connect timeout");
            }
            x86_64::instructions::hlt();
        }
    }
}
